import type { Hooks } from '@opencode-ai/plugin';
import type { ProblemSolvingBrain } from '../../problem-solving/problem-solving-brain.js';
import { isMantaAgent } from '../../shared/agent-identity.js';
import { getCurrentAgent } from './agent-state.js';
import type { StateStore } from '../../shared/state-store.js';
import { getT1Injectables, hasRecoveryCheckpoint } from '../../shared/manta-identity-synthesizer.js';
import { formatMantaIdentityHeader } from '../../shared/manta-identity-header.js';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { mantaError } from '../../shared/manta-logger.js';

let globalBrain: ProblemSolvingBrain | null = null;
let lastUserMessage: string = '';
let lastMantaAgent: string = '';

export function setProblemSolvingBrain(b: ProblemSolvingBrain): void { globalBrain = b; }
let mantaIdentityHeaderValue: string = '';
export function setMantaIdentityHeader(h: string): void { mantaIdentityHeaderValue = h; }
export function setLastUserMessage(msg: string): void { lastUserMessage = msg; }
export function setLastMantaAgent(agent: string): void { lastMantaAgent = agent; }

function updateSoCPreservation(): void {
  try {
    const dir = path.join(process.cwd(), '.manta', 'compaction-survival');
    fs.mkdirSync(dir, { recursive: true });
    const filePath = path.join(dir, 'SoC_PRESERVATION.md');
    const ts = new Date().toISOString();
    const entry = `### Injection: ${ts}\n- **Pattern:** Identity injected via system.transform\n- **Context:** Agent identity binding + T1 warheads applied\n- **Source:** system-transform-hook.ts\n\n`;

    let existing = '';
    try { existing = fs.readFileSync(filePath, 'utf-8'); } catch {}

    // Keep last 50 entries, prepend new one
    const lines = (entry + existing).split('\n');
    const truncated = lines.slice(0, 500).join('\n'); // ~50 entries max
    fs.writeFileSync(filePath, truncated);
  } catch (e) {
    mantaError('Failed to update SoC_PRESERVATION.md:', e);
  }
}

export function createSystemTransformHook(stateStore?: StateStore): Hooks['experimental.chat.system.transform'] {
  return async (input: any, output: any) => {
    const sys = output as { system: string[] };
    if (!Array.isArray(sys.system)) return;
    const sessionId = input?.sessionID || '';
    const agentFromInput = (input as any)?.agent || (input as any)?.agentName || (input as any)?.session?.agentName || '';
    const agent = getCurrentAgent(sessionId) || agentFromInput || lastMantaAgent || '';
    const TRANSITION_KEY = 'manta-last-primary';
    let prevPrimary: string | undefined;
    try {
      prevPrimary = stateStore?.get(TRANSITION_KEY, 'manta-state') as string | undefined;
    } catch (e) {
      mantaError('system-transform: failed to read transition key:', e);
    }
    const currAgentName = agent || '';
    const currPrimary = currAgentName.split('-')[0].split('_')[0];
    const isNowManta = isMantaAgent(currAgentName) || currPrimary === 'manta';
    const wasOtherAgent = prevPrimary && prevPrimary !== 'manta' && prevPrimary !== currPrimary;

    if (isNowManta && wasOtherAgent) {
      const transitionNote = [
        `[AGENT TRANSITION — ${prevPrimary} → manta]`,
        `Previous primary agent: "${prevPrimary}". Current agent: "manta".`,
        `The conversation above was generated by "${prevPrimary}".`,
        `Respond as manta. Your identity: MANTA v2.2.2.`,
        `Do NOT identify as or continue work from "${prevPrimary}".`,
        `[END AGENT TRANSITION]`,
      ].join('\n');
      sys.system.push(transitionNote);
    }

    if (currPrimary) {
      try {
        stateStore?.set(TRANSITION_KEY, currPrimary, 'manta-state');
      } catch (e) {
        mantaError('system-transform: failed to write transition key:', e);
      }
    }

    if (!isMantaAgent(agent)) {
      const mantaPatterns = [
        /MANTA IDENTITY BINDING/i,
        /MANTA LOOP STATUS/i,
        /MANTA PSM MANDATE/i,
        /MANTA v?\d[\w.]*\s*IDENTITY/i,
        /You are MANTA/i,
      ];
      for (let i = sys.system.length - 1; i >= 0; i--) {
        const s = sys.system[i];
        if (typeof s === 'string' && mantaPatterns.some((p: RegExp) => p.test(s))) {
          sys.system.splice(i, 1);
        }
      }
      return;
    }

    const hasIdentity = sys.system.some((s: string) =>
      typeof s === 'string' && s.startsWith('[AGENT IDENTITY BINDING]')
    );
    if (hasIdentity) return;

    const identityHeader = formatMantaIdentityHeader();

    const runtimeDefaults = [
      'You are opencode',
      'interactive CLI tool',
      'software engineering tasks',
    ];
    let replaced = false;
    for (let i = 0; i < sys.system.length; i++) {
      const s = sys.system[i];
      if (typeof s === 'string' && runtimeDefaults.some(d => s.includes(d))) {
        sys.system[i] = identityHeader;
        replaced = true;
        break;
      }
    }
    if (!replaced) {
      sys.system.unshift(identityHeader);
    }

    try {
      const t1 = getT1Injectables();
      if (t1) {
        const t1Warheads: string[] = [];
        if (t1.identityWarhead) {
          t1Warheads.push(t1.identityWarhead);
        }
        if (t1.enforcementWarhead) {
          t1Warheads.push(t1.enforcementWarhead);
        }
        if (t1.gateWarhead) {
          t1Warheads.push(t1.gateWarhead);
        }
        if (t1.RuntimeGradeEngineerWarhead) {
          t1Warheads.push(t1.RuntimeGradeEngineerWarhead);
        }
        if (t1.focusWarhead) {
          t1Warheads.push(t1.focusWarhead);
        }
        if (hasRecoveryCheckpoint() && t1.recoveryWarhead) {
          t1Warheads.push(t1.recoveryWarhead);
        }
        if (t1Warheads.length > 0) {
          sys.system.splice(1, 0, ...t1Warheads);
        }
      }
    } catch (e) {
      mantaError('Failed to inject T1 warheads:', e);
    }

    // Update SoC preservation log after identity injection
    updateSoCPreservation();

    // Worker-scoped identity for subagents
    if (agent === 'manta-plan') {
      const planIdentity = [
        '[WORKER SCOPE: manta-plan — Read-Only Analysis Brain]',
        'You are the MANTA Plan Brain — a read-only analysis and planning subagent.',
        'You CANNOT write code, edit files, or run bash commands.',
        'Your tools: read, glob, grep, webfetch, manta-hive, manta-vision, manta-code-review, ps-mode-*, checkpoint.',
        'You MUST use PSM (ps-mode-layer) for all analysis — start at Layer 1.',
        'Output JSON: analysis, executionPlan, gateCriteria.',
        'Return ONLY the JSON — no conversational fluff.',
        '[END WORKER SCOPE]',
      ].join('\n');
      if (!sys.system.some((s: string) => typeof s === 'string' && s.includes('WORKER SCOPE: manta-plan'))) {
        sys.system.push(planIdentity);
      }
    } else if (agent === 'manta-exec') {
      const execIdentity = [
        '[WORKER SCOPE: manta-exec — Execution Brain]',
        'You are the MANTA Execution Brain — a full-dev implementation subagent.',
        'You implement EXACTLY from the plan provided. No deviations.',
        'Your tools: read, write, edit, bash, glob, grep, manta-spawn-container, manta-test-runner, manta-runtime-audit, manta-code-audit, manta-code-review, manta-vision, checkpoint.',
        'If stuck, respond EXACTLY: EXECUTION_STUCK: <tried> | <happened> | <needed>',
        'Do NOT use task tool — only orchestrator spawns subagents.',
        '[END WORKER SCOPE]',
      ].join('\n');
      if (!sys.system.some((s: string) => typeof s === 'string' && s.includes('WORKER SCOPE: manta-exec'))) {
        sys.system.push(execIdentity);
      }
    }

    if (agent === 'manta-plan') {
      const psmMandate = `[MANTA PSM MANDATE] You MUST use ps-mode-layer to advance through PSM layers. Start at Layer 1 (Assumption). Your first action must be to submit Layer 1 output using ps-mode-layer action=submit layer=1 content="<analysis>". Do NOT proceed without PSM layer submission.`;
      if (!sys.system.some((s: string) => typeof s === 'string' && s.includes('MANTA PSM MANDATE'))) {
        sys.system.push(psmMandate);
      }
    }

    const identityPatterns = [
      /SHARK\s+v?\d[\w.]*\s*IDENTITY/i,
      /KRAKEN\s+v?\d[\w.]*\s*IDENTITY/i,
      /TRIDENT\s+v?\d[\w.]*\s*IDENTITY/i,
      /SPIDER\s+v?\d[\w.]*\s*IDENTITY/i,
      /SHARK IDENTITY BINDING/i,
      /KRAKEN IDENTITY BINDING/i,
      /TRIDENT IDENTITY BINDING/i,
      /SPIDER IDENTITY BINDING/i,
      /HYDRA IDENTITY BINDING/i,
      /HERMES IDENTITY BINDING/i,
      /You are SHARK/i,
      /You are TRIDENT/i,
      /You are KRAKEN/i,
      /You are SPIDER/i,
    ];
    for (let i = sys.system.length - 1; i >= 0; i--) {
      const s = sys.system[i];
      if (typeof s === 'string') {
        const isNonManta = identityPatterns.some((p: RegExp) => p.test(s));
        if (isNonManta) {
          sys.system.splice(i, 1);
        }
      }
    }
  };
}
